# Custom Language File for Launcher Customizer

[ejs.app]
title = "Choya Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/blueearthcat/Choya-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/GGr6xw2Fxr"

[ejs.settings]
sourceGithubLink = "https://github.com/blueearthcat/Choya-Launcher"
supportLink = "https://github.com/blueearthcat/Choya-Launcher/issues"

[ejs.welcome]
welcomeHeader = "초야 서버에 오신걸 환영합니다."
welcomeDescription = "스트리머와 시청자가 함께하는 서버"
welcomeDescCTA = "지금 바로 접속하세요!"
